### Program speed

Modern computers are very fast; most of the time tasks run so quickly we don't notice whether they run in microseconds or milliseconds. But you have likely encountered programs that do take some time, and if you do enough computational physics you will surely encounter more. It is worth considering some factors affecting the speed of our programs.

Even inefficient code still runs fairly quickly. Often brute force mathematics is the simple computational solution. But one of the themes in this course is brute force solutions typically run up against practical limits fairly quickly.

In [1]:
import time
import numpy as np

In [2]:
start = time.time()

slow = {i: i for i in range(int(5e6))}
print(time.time() - start)

for k in slow.keys():
    slow[k] += 1

print(time.time() - start)

0.1295638084411621
0.3361027240753174


In [3]:
start = time.time()

slow = [i for i in range(int(5e6))]
print(time.time() - start)

for i in range(int(5e6)):
    slow[i] += 1

print(time.time() - start)

0.10616493225097656
0.3029930591583252


In [5]:
start = time.time()

slow = np.array(5e6)
print(time.time() - start)

slow += 1

print(time.time() - start)

0.0015058517456054688
0.0017619132995605469


### Example 4.2

The book provides an example illustrating some good practices for efficient programming, how quickly a "good" solution can be arrived at computationally, and some limits of running **many** calculations.

In [6]:
terms = 1000
beta = 1 / 100
s = 0.0
z = 0.0

for n in range(terms):
    E = n + 0.5
    # I've added a float cast here because numpy always returns a numpy object never a float/int
    weight = float(np.exp(-beta*E))
    s += weight * E
    z += weight

print(s/z)

99.95543134093475


I'm going to rearrange the code in the book to make changing the number of terms easier, then we'll try different numbers of terms.

In [7]:
# constant, it's ok to define these here
beta = 1 / 100

def oscillator(terms):
    s = 0.0
    z = 0.0
    for n in range(terms):
        E = n + 0.5
        # I've added a float cast here because numpy always returns a numpy object never a float/int
        weight = float(np.exp(-beta*E))
        s += weight * E
        z += weight

    print(terms, s/z)

begin = time.time()
oscillator(1000)
print(time.time() - begin)
oscillator(int(1e6))
print(time.time() - begin)
oscillator(int(1e7))
print(time.time() - begin)
oscillator(int(1e8))
print(time.time() - begin)

1000 99.95543134093475
0.0008249282836914062
1000000 100.00083333194436
0.33200597763061523
10000000 100.00083333194436
3.5229780673980713
100000000 100.00083333194436
35.77028679847717


In [8]:
a = np.arange(0, 10000, 1).reshape((100,100))
b = np.arange(2, 10002, 1).reshape((100,100))
print(a.shape, b.shape)

(100, 100) (100, 100)


In [9]:
N = 100
C = np.zeros([N, N])

begin = time.time()
for i in range(N):
    for j in range(N):
        for k in range(N):
            C[i,j] += a[i,k] * b[k,j]

print(time.time() - begin)

begin = time.time()

print(np.matmul(a,b) - C)
print(time.time() - begin)

0.2731339931488037
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0.0014619827270507812
